# Generated by Django 4.0.4 on 2022-05-26 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0004_alter_blog_id_alter_comment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='img',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
