# Generated by Django 3.2 on 2022-06-03 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0007_usertoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='img_link',
            field=models.CharField(default=None, max_length=300),
            preserve_default=False,
        ),
    ]
